### ISSUE TITLE
Having problems starting the app

### ISSUE THREAD

**Issue by tim-maguire** [peterfiorito/spare-room#1]
Hello Pedro. 

We're having issues getting this up and running. 
After following your steps we're getting: 
```
The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
```

The after installing the clit and running `npm run start` again we're getting:
```
TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (/Users/tvm/code/dev_tests/spare-room/node_modules/webpack-dev-server/lib/Server.js:131:49)
    at new Server (/Users/tvm/code/dev_tests/spare-room/node_modules/webpack-dev-server/lib/Server.js:144:5)
    at startDevServer (/Users/tvm/code/dev_tests/spare-room/node_modules/webpack-dev-server/bin/webpack-dev-server.js:355:14)
    at processOptions (/Users/tvm/code/dev_tests/spare-room/node_modules/webpack-dev-server/bin/webpack-dev-server.js:309:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
```

I'm guessing you have `webpack-cli` installed globally?

Not sure about the 2nd issue. Could it be different node versions?

I'm on `10.11.0` at the moment.

Thanks, 

Tim.

**Comment by peterfiorito** [comment]
Hi @tim-maguire sorry about that. I had a warning from github regarding a vulnerability in Webpack. I updated the package and this caused this issue.
Rolled back, should be working correctly now. Let me know if the issue is fixed!
